### PR TITLE
Only use IPv6 sysctls when $family = 6

### PR DESCRIPTION
**Pull request by aanriot**
Arnaud,

Here is a minor fix to avoid errors such as:

```
sysctl: cannot stat /proc/sys/net/ipv6/conf/eth0_33/autoconf: No such file or directory
```

Feel free to merge it, if it makes sense.

### CODE REVIEW

**Comment by gcolpart** [comment]
IMHO IPv6 sysctls are also relevant for $family = 4.
The script should verify if IPv6 is enabled on system.
Also these IPv6 sysctls should not be in the loop "for".
Then I suggest:

```
        for ip in $ips; do
            ip -$family addr add $ip dev $interface
        done
        if [ -f /proc/net/if_inet6 ]; then
            sysctl -w net/ipv6/conf/$interface/autoconf=0
            sysctl -w net/ipv6/conf/$interface/accept_ra=0
            sysctl -w net/ipv6/conf/$interface/forwarding=1
        fi
        ip link set dev $interface up
```

I let Arnaud decide how to fix it.

**Comment by aanriot** [comment]
Hello,

Indeed, it seems to be a more effective patch, the sysctls are in a better place out of the loop.

**Comment by o0n** [comment]
Hello Alexandre and Gregory,

sysctl were wrongly setted in vrrp_switch.sh and I see that the init hook was never called by the daemon.

I applied your recommandations in the fix and test if IPv6 is enabled on system, in commit 080965f.

Now sysctl values are setted in init state, only once, net.ipv(4|6).conf.all.\* for the existing interfaces and net.ipv(4|6).conf.default.\* for new created interfaces.

Warning : currently, these values could be modified by another service, like a reload of a custom firewall script.

Thanks for your feedback, I close the PR.

**Comment by aanriot** [comment]
Thanks Arnaud.

**Pull request closed without merging**
